version: "3.3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: 172.17.0.1 
      PMA_PORT: 3306
  php7.3:
    image: quay.io/vesica/php73:latest
    container_name: php73
    volumes:
      - ./var/www/html:/var/www/html
    ports:
      - 80:8080 
     

